/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java.gui;

import ar.com.eduit.curso.java.utils.swing.Box;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.DefaultMetalTheme;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.metal.OceanTheme;
import javax.swing.plaf.metal.*;





/**
 *
 * @author sunnyclat
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        
        initComponents();
              
      //  this.setExtendedState(JFrame.MAXIMIZED_BOTH);  //muestra en pantalla completa
        
       this.setBounds(100,100,800,800); //x y ancho alto
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jVentanas = new javax.swing.JMenu();
        JAlumnos = new javax.swing.JMenuItem();
        JCursos = new javax.swing.JMenuItem();
        jOpciones = new javax.swing.JMenu();
        JAcerca = new javax.swing.JMenuItem();
        JSalir = new javax.swing.JMenuItem();

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de un Colegio");

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jVentanas.setText("Formularios");

        JAlumnos.setText("Alumnos");
        JAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAlumnosActionPerformed(evt);
            }
        });
        jVentanas.add(JAlumnos);

        JCursos.setText("Cursos");
        JCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCursosActionPerformed(evt);
            }
        });
        jVentanas.add(JCursos);

        jMenuBar1.add(jVentanas);

        jOpciones.setText("Opciones");

        JAcerca.setText("Acerca");
        JAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAcercaActionPerformed(evt);
            }
        });
        jOpciones.add(JAcerca);

        JSalir.setText("Salir");
        JSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSalirActionPerformed(evt);
            }
        });
        jOpciones.add(JSalir);

        jMenuBar1.add(jOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAcercaActionPerformed
    
        //Ponemos lo que aparecera en el pop up del boton acerca.
        
     //   JOptionPane.showMessageDialog(this, "Sistema de un colegio. By samu.");
        
        Box.msg(this,"Sistema de un colegio. By samu.");
    }//GEN-LAST:event_JAcercaActionPerformed

    private void JSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSalirActionPerformed
      
        //boton salir para salir del programa.
        
        System.exit(0);
        
        
    }//GEN-LAST:event_JSalirActionPerformed

    private void JAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAlumnosActionPerformed
       
        FormAlumnos fra=new FormAlumnos();
        jEscritorio.add(fra);  //agregamos el panel de escritorio (para las ventana interna de alumnos)
        fra.setVisible(true);  //con esto hago visible el formulario
       
        
        Dimension desktopSize = jEscritorio.getSize();
        Dimension FrameSize = fra.getSize();
        fra.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        fra.show();
      
    }//GEN-LAST:event_JAlumnosActionPerformed

    private void JCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCursosActionPerformed
        
        FormCursos frc=new FormCursos();
        jEscritorio.add(frc);  //lo mismo hago para cursos
        
        

        
        frc.setVisible(true);
        frc.setOpaque(rootPaneCheckingEnabled);
     
 
               Dimension desktopSize = jEscritorio.getSize();
        Dimension FrameSize = frc.getSize();
        frc.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        frc.show();
        
    }//GEN-LAST:event_JCursosActionPerformed
       
    
    // SI ELIJO EL LOOKANDFEEL METAL, PUEDO USAR LOS THEME: DEFAULTMETAL Y OCEAN (ESTE ULTIMO ES COMO SI NO ANDARA)
    
    //SINO PUEDO ELEGIR LOS LOOKANDFEEL: SYSTEM,MOTIF Y GTK (ESTE ULTIMO ME TIRA ERROR DE LIBRERIA)
    
    
    final static String LOOKANDFEEL="Motif";
              final static String THEME="DefaultMetal";
              
              
              
              
              
              
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        
        

     String lookAndFeel = null;
       
        if (LOOKANDFEEL != null) {
            
            
            
            if (LOOKANDFEEL.equals("Metal")) {
             
                
                //lookAndFeel = UIManager.getCrossPlatformLookAndFeelClassName();
              //  an alternative way to set the Metal L&F is to replace the 
              // previous line with:
               lookAndFeel = "javax.swing.plaf.metal.MetalLookAndFeel";
                
            }
            
            else if (LOOKANDFEEL.equals("System")) {
                lookAndFeel = UIManager.getSystemLookAndFeelClassName();
            } 
            
            else if (LOOKANDFEEL.equals("Motif")) {
                lookAndFeel = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
            } 
            
            else if (LOOKANDFEEL.equals("GTK")) { 
                lookAndFeel = "com.sun.java.swing.plaf.gtk.GTKLookAndFeel";
            } 
            
            else {
                System.err.println("Unexpected value of LOOKANDFEEL specified: "
                                   + LOOKANDFEEL);
                lookAndFeel = UIManager.getCrossPlatformLookAndFeelClassName();
            }

            
            
            
            try {
            	
            	
                UIManager.setLookAndFeel(lookAndFeel);
                
                
        
                
                // If L&F = "Metal", set the theme
                
                if (LOOKANDFEEL.equals("Metal")) {
                    
                  if (THEME.equals("DefaultMetal"))
                     MetalLookAndFeel.setCurrentTheme(new DefaultMetalTheme());
                  else if (THEME.equals("Ocean"))
                     MetalLookAndFeel.setCurrentTheme(new OceanTheme());
                  
                  /*
                  else
                     MetalLookAndFeel.setCurrentTheme(new TestTheme());
                   */  
                  
              //    else if
                  
                  UIManager.setLookAndFeel(new MetalLookAndFeel()); 
                }	
                	
                	
                  
                
            } 
            
            catch (ClassNotFoundException e) {
                System.err.println("Couldn't find class for specified look and feel:"
                                   + lookAndFeel);
                System.err.println("Did you include the L&F library in the class path?");
                System.err.println("Using the default look and feel.");
            } 
            
            catch (UnsupportedLookAndFeelException e) {
                System.err.println("Can't use the specified look and feel ("
                                   + lookAndFeel
                                   + ") on this platform.");
                System.err.println("Using the default look and feel.");
            } 
            
            catch (Exception e) {
                System.err.println("Couldn't get specified look and feel ("
                                   + lookAndFeel
                                   + "), for some reason.");
                System.err.println("Using the default look and feel.");
                e.printStackTrace();
            }
            
            
            
        
        
        
        
        
    }

                
        
        
        //DENTRO DEL TRY CATCH TENGO LA SKIN (EN JAVA SE LLAMA LOOK AND FEELS A LAS SKINS), PUEDO COMENTARLA PARA DESACTIARLA SI QUIERO*/
        
        /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
       
        */
        
        //</editor-fold>

        
        /* Create and display the form */
        
        
        
        
        //COMENTANDO ESTO, HACEMOS QUE EL PROCESO SE EJECUTE EN UN HILO DISTINTO.
        
        /*
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
        */
        
        
        //Y SE EJECUTE EN ESTE NUEVO HILO.
        new FormularioPrincipal().setVisible(true);  //con esto lo estoy haciendo visible en el hilo principal de ejecucion
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JAcerca;
    private javax.swing.JMenuItem JAlumnos;
    private javax.swing.JMenuItem JCursos;
    private javax.swing.JMenuItem JSalir;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jOpciones;
    private javax.swing.JMenu jVentanas;
    // End of variables declaration//GEN-END:variables
}

