
package Java.gui;

import BaseDatos.ConnectorMySQL;
import Entities.Alumnos;
import Entities.Curso;
import Repositories.interfaces.I_AlumnoR;
import Repositories.interfaces.I_CursoR;
import Repositories.interfaces.jdbc.AlumnoR;
import Repositories.interfaces.jdbc.CursoR;
import ar.com.eduit.curso.java.utils.swing.Box;
import ar.com.eduit.curso.java.utils.swing.Table;
import ar.com.eduit.curso.java.utils.swing.Validator;
import javax.swing.JTable;



/**
 *
 * @author sunnyclat
 */
public class FormAlumnos extends javax.swing.JInternalFrame {
    
    
    
I_AlumnoR ar;
I_CursoR cr;


 
    public FormAlumnos() {
   
        //con esto podre achicar y mover las ventanas
        
        
        
        // debe invocar un super y este debe estar antes de initcomponents
        
        super(
        
        
        "Formulario de Alumnos",            //titulo
                false,                              // resizable, el usuario puede manipular la ventana
                true,                              //   closable, se puede cerrar
                true,                              //        maximizable, inicia maximizado
                true                              //               iconable, inicia minimizado
        
             
        
        
        
        
        
        
        
        );
        
        
             initComponents();
             
                       this.setBounds(0,0,600,700);
      
        
        ar=new AlumnoR(ConnectorMySQL.getConnection());
        cr=new CursoR(ConnectorMySQL.getConnection());
        
        
            tblAlumnos.setAutoscrolls(closable);
        
       
       
            tblAlumnos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

              
                 //     tblAlumnos.getColumnModel().getColumn(0).setPreferredWidth(27);
         
                 
          //       tblAlumnos.getColumnModel().getColumn(0).setMinWidth(WIDTH);
         //       tblAlumnos.getColumnModel().getColumn(1).setPreferredWidth(120);
         //        tblAlumnos.getColumnModel().getColumn(2).setPreferredWidth(100);
              //    tblAlumnos.getColumnModel().getColumn(3).getMaxWidth()
                          
                 //        tblAlumnos.getColumnModel().getColumn(3).getResizable();
                     
            //  tblAlumnos.getColumnModel().getColumn(3).setPreferredWidth(200);
    // tblAlumnos.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
        cargarTable();
          

    }

    
    
    private void cargarTable(){
        
        
           new Table<Alumnos>().cargar(tblAlumnos, ar.getAll());
           
           
           
           //asi iremos actualizando el combo cmbcursos en el caso que se hayan guardado otros elementos despues de haberlo usado antes
        cmbCursos.removeAllItems();
        
        
        
        cr.getAll().forEach(cmbCursos::addItem);
        
    }
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarApe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombAlum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApeAlum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEdadAlum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbCursos = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        jerase = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAlumnos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblAlumnos);

        jLabel1.setText("Apellido:");

        txtBuscarApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarApeKeyReleased(evt);
            }
        });

        jLabel2.setText("Nombre:");

        txtNombAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombAlumActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido:");

        jLabel4.setText("Edad:");

        jLabel6.setText("Curso:");

        cmbCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCursosActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jerase.setText("Borrar");
        jerase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeraseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarApe, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236)
                        .addComponent(jerase)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbCursos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEdadAlum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApeAlum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombAlum, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtNombAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApeAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEdadAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jerase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarApeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarApeKeyReleased
        
        
   new Table<Alumnos>().cargar(tblAlumnos, ar.getLikeApellido(txtBuscarApe.getText()));
        
        
        
        
    }//GEN-LAST:event_txtBuscarApeKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        
        if(validar()){
            
            //recordar cambiar el parametro del combobox de string al nombre del enumerador. Sino tirara error de conversion a string.
            //En este caso, le ponemos el nombre del generic (<curso>)
            
            Alumnos alumno= new Alumnos(
                    
                    txtNombAlum.getText(),
                    txtApeAlum.getText(),
                    Integer.parseInt(txtEdadAlum.getText()),
                    cmbCursos.getItemAt(cmbCursos.getSelectedIndex() )
            //si tenemos un error en el getitemat es probable que no hayamos importado la clase curso.
                    
            );    
                    
              ar.save(alumno);
            limpiar();
            
            cargarTable(); //va adentro del validar
            
            
            lblInfo.setText("Se dio de alta un alumno codigo: "+alumno.getCodigo());
            
            
       
            
        }else{
            lblInfo.setText("No se pudo ingresar el alumno.");
        }     
                    
                    
        
        
         
        
      
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCursosActionPerformed

    private void jeraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeraseActionPerformed
   
        
        if(tblAlumnos.getSelectedRow()==-1) return;
        
        
        if(Box.confirm(this, "Esta seguro que desea borrar un curso?")){
            
            ar.remove(
                    ar.getByCodigo(
                            Integer.parseInt(tblAlumnos.getValueAt(tblAlumnos.getSelectedRow(),0)+"")
                    )
            );
        }
        cargarTable();
    }//GEN-LAST:event_jeraseActionPerformed

    private void txtNombAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombAlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombAlumActionPerformed


    public boolean validar(){
        
        
        
        if(!new Validator(txtNombAlum).length(2,25)) return false;
        
        
        if(!new Validator(txtApeAlum).length(2,25)) return false;
        
        
        if(!new Validator(txtEdadAlum).isInteger(18,70)) return false;
        
        
        
        
        return true;
    }
    
    
    private void limpiar(){
        
        txtNombAlum.setText("");
        txtApeAlum.setText("");
        txtEdadAlum.setText("");
        cmbCursos.setSelectedIndex(0);
          txtNombAlum.requestFocus();
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<Curso> cmbCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jerase;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTextField txtApeAlum;
    private javax.swing.JTextField txtBuscarApe;
    private javax.swing.JTextField txtEdadAlum;
    private javax.swing.JTextField txtNombAlum;
    // End of variables declaration//GEN-END:variables

}


